os:
  - linux
dist: xenial
services: postgresql
addons:
  postgresql: "10"
language: java
install: true
jdk:
  - openjdk11
sudo: false
branches:
  only:
    - main
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
before_install:
  - java -version
script:
  - mvn clean test
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
